#!/usr/bin/env python3
"""Generate (and compile) the type descriptions the overlap extension ships.

libmutter is built with hidden visibility, but the test-export macro expands to a real
export, so the four symbols the extension needs are ordinary dynamic symbols in the
shipped library -- absent from the introspection data, not from the library.  A GNOME
Shell extension can prepend its own search path and load a type description it ships
itself, which is what these files are.

Two properties of what is emitted here matter more than anything else in this tree:

**No pointer is ever declared as a pointer.**  Every pointer field in Mutter's private
structures is declared `guint64`, so reading one yields a *number* and gjs never
dereferences anything on our behalf.  Stepping from one struct to the next goes through
`g_memdup2(ptr, n)` -- a bounded copy of exactly n bytes -- and `g_strndup(ptr, n)` for
the connector strings, which lets the extension range-check the number against
`/proc/self/maps` before any address is read at all.  A wrong offset then produces
garbage or a refusal, not a SIGSEGV; with pointers declared as pointers it produced a
dead gnome-shell (measured, GNOME 50.1, docs/Technical.md section 6).

**Nothing that can write ~/.config/monitors.xml is declared.**
`meta_monitor_config_manager_save_current()` is not in the file, and neither is any
other `*save*` symbol, so no code in the extension can reach the writer even by
mistake.  `tests/test_gnome_overlap.py` asserts that about the shipped .gir and about
the shipped .typelib bytes.

The layout below is measured, not assumed (docs/Technical.md section 6): `parent_config`
and `switch_config` were proved with sentinels written through the exported accessors.
`logical_monitor_configs` is at offset 40 on both mutter 14 and mutter 18; the tail and
the total size are not the same, which is exactly why there is one description per
generation and why the extension refuses to run one against the other.

    offset  mutter 14 (GNOME 46)      mutter 18 (GNOME 50)
    0..23   GObject                   GObject
    24      parent_config             parent_config
    32      key                       key
    40      logical_monitor_configs   logical_monitor_configs
    48      disabled_monitor_specs    disabled_monitor_specs
    56      flags                     (unused)
    60      layout_mode               (unused)
    64      switch_config             (unused)
    68      padding                   layout_mode
    72      --                        switch_config
    76      --                        padding
    size    72                        80

Usage:  python3 gnome/overlap-typelib/gen-gir.py [OUTDIR]
        (OUTDIR defaults to gnome/fuckwayland-overlap@fuckwayland/typelib)
        python3 gnome/overlap-typelib/gen-gir.py --check
        python3 gnome/overlap-typelib/gen-gir.py --from-header PATH [--gen N]

Needs `g-ir-compiler` (Ubuntu: libgirepository1.0-dev).  The compiled typelibs are
checked in because no desktop has that package installed; `--check` recompiles and
compares, which is how CI notices a .gir edited without a rebuild.

`--from-header` is the answer to a `typelib` or `sentinel` refusal after a GNOME
upgrade, and the only route by which a new generation should ever be added.  It reads
mutter's own `src/backends/meta-monitor-config-manager.h` -- the release's source, not
the running compositor -- lays `struct _MetaMonitorsConfig` out under the x86-64 rules
and prints the offsets, the instance size and the one `BUILDS` line that describes it.
With `--gen N` it compares that against what is already shipped for generation N and
says whether they agree.

**It derives from source and never from a live libmutter, and that is the whole
point.**  A description generated by asking the compositor about itself would agree
with the compositor by construction: `struct-size` would pass because it was told the
size, and `sentinel` could only be satisfied by searching offsets until the marker
turned up, which is a search that confirms itself.  The independence of the shipped
description from the build it is checked against is what makes those two checks mean
anything -- it is why a wrong-generation description was caught before a byte was read
(measured on 24.04 and 26.04) -- and self-derivation would spend it to save a human
one afternoon per GNOME release.  So: derive the numbers here, from the release's
header, then prove them on a three-head VM as docs/Technical.md section 6 describes,
and only then add the generation to the four allowlists.
"""

import hashlib
import os
import subprocess
import sys

# generation -> (soname, ints between disabled_monitor_specs and layout_mode)
#   mutter 14: one (flags)      -> 56 + 4 + 12 = 72
#   mutter 18: three           -> 56 + 12 + 12 = 80
BUILDS = {
    14: ("libmutter-14.so.0", 1),
    18: ("libmutter-18.so.0", 3),
}

HEAD = '''<?xml version="1.0"?>
<!-- GENERATED by gnome/overlap-typelib/gen-gir.py -- do not edit by hand.
     Mutter {gen}'s private monitor-configuration structures, described so that no
     pointer in them is ever followed by the type system.  See that script. -->
<repository version="1.2"
            xmlns="http://www.gtk.org/introspection/core/1.0"
            xmlns:c="http://www.gtk.org/introspection/c/1.0"
            xmlns:glib="http://www.gtk.org/introspection/glib/1.0">
  <include name="GObject" version="2.0"/>
  <namespace name="{ns}" version="1.0" shared-library="{lib}"
             c:identifier-prefixes="Meta" c:symbol-prefixes="meta">

    <!-- MetaMonitorsConfig.  Every pointer is a guint64: a number, never a
         dereference. -->
    <record name="ConfigN" c:type="MetaMonitorsConfigN">
      <field name="g_class" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="ref_count" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="qdata" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="parent_config" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="key" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="logical_monitor_configs" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="disabled_monitor_specs" writable="1"><type name="guint64" c:type="guint64"/></field>
{tail}      <field name="layout_mode" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="switch_config" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="tail_pad" writable="1"><type name="gint" c:type="gint"/></field>
    </record>

    <!-- GList -->
    <record name="NodeN" c:type="MetaNodeN">
      <field name="data" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="next" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="prev" writable="1"><type name="guint64" c:type="guint64"/></field>
    </record>

    <!-- MetaLogicalMonitorConfig.  x is at +0 and y at +4: the only two words
         this extension ever writes. -->
    <record name="LMCN" c:type="MetaLMCN">
      <field name="x" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="y" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="width" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="height" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="monitor_configs" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="transform" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="scale" writable="1"><type name="gfloat" c:type="gfloat"/></field>
      <field name="is_primary" writable="1"><type name="gboolean" c:type="gboolean"/></field>
      <field name="is_presentation" writable="1"><type name="gboolean" c:type="gboolean"/></field>
    </record>

    <!-- MetaMonitorConfig -->
    <record name="MCN" c:type="MetaMCN">
      <field name="monitor_spec" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="mode_spec" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="enable_underscanning" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="pad" writable="1"><type name="gint" c:type="gint"/></field>
    </record>

    <!-- MetaMonitorSpec -->
    <record name="MSN" c:type="MetaMSN">
      <field name="connector" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="vendor" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="product" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="serial" writable="1"><type name="guint64" c:type="guint64"/></field>
    </record>

'''

TAIL_FIELD = ('      <field name="u{off}" writable="1">'
              '<type name="gint" c:type="gint"/></field>\n')


def _memdup(name, ret):
    """g_memdup2(number, n) -> a copy of exactly n bytes, read as `ret`."""
    return f'''    <function name="{name}" c:identifier="g_memdup2">
      <return-value transfer-ownership="none"><type name="{ret}" c:type="gpointer"/></return-value>
      <parameters>
        <parameter name="mem" transfer-ownership="none"><type name="guint64" c:type="guint64"/></parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>
'''


BODY = (
    _memdup('dup_cfg', 'ConfigN')
    + _memdup('dup_node', 'NodeN')
    + _memdup('dup_lmc', 'LMCN')
    + _memdup('dup_mc', 'MCN')
    + _memdup('dup_ms', 'MSN')
    + '''    <!-- a bounded copy of at most n bytes of a string -->
    <function name="strn" c:identifier="g_strndup">
      <return-value transfer-ownership="none"><type name="utf8" c:type="char*"/></return-value>
      <parameters>
        <parameter name="s" transfer-ownership="none"><type name="guint64" c:type="guint64"/></parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>

    <!-- the address of an object, as a number (g_object_ref returns its argument);
         every addr() is balanced by an unref_addr() -->
    <function name="addr" c:identifier="g_object_ref">
      <return-value transfer-ownership="none"><type name="guint64" c:type="guint64"/></return-value>
      <parameters><parameter name="o" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="unref_addr" c:identifier="g_object_unref">
      <return-value transfer-ownership="none"><type name="none" c:type="void"/></return-value>
      <parameters><parameter name="p" transfer-ownership="none"><type name="guint64" c:type="gpointer"/></parameter></parameters>
    </function>

    <!-- reads offset 0 only; GTypeInstance's first word is frozen ABI -->
    <function name="type_name" c:identifier="g_type_name_from_instance">
      <return-value transfer-ownership="none"><type name="utf8" c:type="char*"/></return-value>
      <parameters><parameter name="o" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>

    <!-- the exported-but-not-introspected monitor configuration API -->
    <function name="get_config_manager" c:identifier="meta_monitor_manager_get_config_manager">
      <return-value transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="get_current" c:identifier="meta_monitor_config_manager_get_current">
      <return-value transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="create_linear" c:identifier="meta_monitor_config_manager_create_linear">
      <return-value transfer-ownership="full"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="get_switch_config" c:identifier="meta_monitors_config_get_switch_config">
      <return-value transfer-ownership="none"><type name="gint" c:type="gint"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="set_switch_config" c:identifier="meta_monitors_config_set_switch_config">
      <return-value transfer-ownership="none"><type name="none" c:type="void"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="v" transfer-ownership="none"><type name="gint" c:type="gint"/></parameter></parameters>
    </function>
    <function name="verify" c:identifier="meta_verify_monitors_config" throws="1">
      <return-value transfer-ownership="none"><type name="gboolean" c:type="gboolean"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="apply" c:identifier="meta_monitor_manager_apply_monitors_config" throws="1">
      <return-value transfer-ownership="none"><type name="gboolean" c:type="gboolean"/></return-value>
      <parameters><parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="method" transfer-ownership="none"><type name="gint" c:type="gint"/></parameter></parameters>
    </function>

    <!-- the write: four bytes at an address the reader has already range-checked -->
    <function name="wr" c:identifier="memcpy">
      <return-value transfer-ownership="none"><type name="guint64" c:type="gpointer"/></return-value>
      <parameters>
        <parameter name="dest" transfer-ownership="none"><type name="guint64" c:type="gpointer"/></parameter>
        <parameter name="src" transfer-ownership="none">
          <array c:type="gpointer" length="2"><type name="guint8" c:type="guint8"/></array>
        </parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>
  </namespace>
</repository>
'''
)

# -- deriving a layout from mutter's own header -------------------------------
#
# The x86-64 System V rules, over the handful of types this one struct uses.  A
# type this table does not know is an error and not a guess: the whole value of
# doing the arithmetic here rather than by hand is that it cannot quietly get a
# size wrong, and an unknown type is exactly where a hand derivation goes wrong.
# `--int NAME` adds a 4-byte enum for a header that introduces one.
SIZES = {
    "GObject": (24, 8),                 # GTypeInstance* + ref_count + qdata
    "gboolean": (4, 4), "gint": (4, 4), "int": (4, 4), "guint": (4, 4),
    "unsigned int": (4, 4), "unsigned": (4, 4), "uint32_t": (4, 4),
    "gfloat": (4, 4), "float": (4, 4),
    "gsize": (8, 8), "guint64": (8, 8), "gint64": (8, 8),
    # mutter's own enums, which are ints: named one by one, because "it starts
    # with Meta" is true of the structs as well
    "MetaMonitorsConfigFlag": (4, 4),
    "MetaLogicalMonitorLayoutMode": (4, 4),
    "MetaMonitorSwitchConfigType": (4, 4),
}


def strip_comments(text: str) -> str:
    out, i, n = [], 0, len(text)
    while i < n:
        if text.startswith("/*", i):
            j = text.find("*/", i + 2)
            i = n if j < 0 else j + 2
        elif text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


def struct_fields(header_text: str, name: str = "_MetaMonitorsConfig") -> list:
    """[(type, field name, is pointer)] for one C struct in a header."""
    text = strip_comments(header_text)
    at = text.find("struct %s" % name)
    if at < 0:
        raise SystemExit("gen-gir: no `struct %s` in that header" % name)
    open_at = text.index("{", at)
    close_at = text.index("}", open_at)
    fields = []
    for decl in text[open_at + 1:close_at].split(";"):
        decl = " ".join(decl.split())
        if not decl:
            continue
        if "(" in decl or "[" in decl:
            raise SystemExit("gen-gir: %s: this reads function pointers and arrays no "
                             "better than a human does: %s" % (name, decl))
        pointer = "*" in decl
        words = decl.replace("*", " ").split()
        if len(words) < 2:
            raise SystemExit("gen-gir: %s: cannot read the field `%s`" % (name, decl))
        fields.append((" ".join(words[:-1]), words[-1], pointer))
    return fields


def layout(fields: list) -> tuple:
    """(rows, instance size) for a field list, laid out the way the compiler does.

    rows are (offset, size, type, name)."""
    off, align_max, rows = 0, 1, []
    for ctype, fname, pointer in fields:
        if pointer:
            size = align = 8
        elif ctype in SIZES:
            size, align = SIZES[ctype]
        else:
            raise SystemExit(
                "gen-gir: `%s %s` is a type this does not know the size of.  Add it to "
                "SIZES (or pass --int %s if it is an enum) rather than guessing: a "
                "wrong size here is a wrong offset in a live compositor."
                % (ctype, fname, ctype))
        off = (off + align - 1) // align * align
        rows.append((off, size, ctype + (" *" if pointer else ""), fname))
        off += size
        align_max = max(align_max, align)
    return rows, (off + align_max - 1) // align_max * align_max


#: What the shipped description assumes about every generation, and what
#: `--from-header` refuses to paper over.  If a release breaks one of these the
#: description's *shape* no longer applies, not just its numbers, and the .gir in
#: this directory has to be rewritten by a human who has read the new struct.
SHAPE = [(0, "parent"), (24, "parent_config"), (32, "key"),
         (40, "logical_monitor_configs"), (48, "disabled_monitor_specs")]


def build_from_header(text: str) -> tuple:
    """((soname-less) BUILDS value, rows, size) for a mutter header.

    Returns (ints, rows, size): `ints` is the number of 4-byte slots the
    description fills between `disabled_monitor_specs` and `layout_mode`, which is
    the only thing BUILDS carries besides the soname."""
    rows, size = layout(struct_fields(text))
    at = {name: (off, sz) for off, sz, _t, name in rows}
    for off, name in SHAPE:
        if at.get(name, (None,))[0] != off:
            raise SystemExit(
                "gen-gir: this header puts %s at %s, not %d.  The shipped description "
                "assumes the head of this struct is unchanged; a release that moves it "
                "needs a new .gir written by hand, not a new number."
                % (name, at.get(name, ("absent",))[0], off))
    for name in ("layout_mode", "switch_config"):
        if name not in at or at[name][1] != 4:
            raise SystemExit("gen-gir: no 4-byte %s in this struct" % name)
    lm, sw = at["layout_mode"][0], at["switch_config"][0]
    if sw != lm + 4:
        raise SystemExit("gen-gir: switch_config is at %d, not straight after "
                         "layout_mode at %d" % (sw, lm))
    if lm < 56 or (lm - 56) % 4:
        raise SystemExit("gen-gir: layout_mode is at %d; the description can only "
                         "describe the gap before it in whole 4-byte slots" % lm)
    return (lm - 56) // 4, rows, size


def report_header(path: str, gen) -> int:
    text = open(path, encoding="utf-8", errors="replace").read()
    ints, rows, size = build_from_header(text)
    print("%s" % path)
    for off, sz, ctype, name in rows:
        print("  %3d  %2d  %s %s" % (off, sz, ctype, name))
    print("  instance size %d" % size)
    print("  BUILDS entry:  <generation>: (\"libmutter-<generation>.so.0\", %d)," % ints)
    if gen is None:
        print("  (pass --gen N to compare this against the description shipped for N)")
        return 0
    gen = int(gen)
    if gen not in BUILDS:
        print("  generation %d is not shipped.  Adding one is this description, three "
              "allowlist edits and a measurement, in this order:" % gen)
        print("    1. add %d: (\"libmutter-%d.so.0\", %d) to BUILDS here and re-run this "
              "script with no arguments" % (gen, gen, ints))
        print("    2. SUPPORTED in gnome/fuckwayland-overlap@fuckwayland/rules.js")
        print("    3. SUPPORTED_MAJORS in wxrandr/gnome_overlap.py")
        print("    4. shell-version in gnome/fuckwayland-overlap@fuckwayland/metadata.json")
        print("    5. prove it on a three-head VM before shipping it: docs/Technical.md "
              "section 6, \"If a GNOME upgrade breaks this\", step 5")
        return 1
    want = BUILDS[gen][1]
    if want == ints:
        print("  agrees with the description shipped for libmutter-%d (%d 4-byte slot%s)"
              % (gen, ints, "" if ints == 1 else "s"))
        return 0
    print("  DISAGREES with the description shipped for libmutter-%d: it fills %d slots, "
          "this header wants %d" % (gen, want, ints))
    return 1


FORBIDDEN = ("save", "write", "store", "persist")


def identifiers(text: str) -> list:
    """Every C symbol a type description makes callable."""
    out = []
    for line in text.splitlines():
        i = line.find('c:identifier="')
        if i >= 0:
            out.append(line[i + 14:line.index('"', i + 14)])
    return sorted(set(out))


def gir(gen: int) -> tuple:
    """(namespace, gir text) for one mutter generation."""
    lib, ints = BUILDS[gen]
    ns = "FwOverlap%d" % gen
    tail = "".join(TAIL_FIELD.format(off=56 + 4 * i) for i in range(ints))
    text = HEAD.format(gen=gen, ns=ns, lib=lib, tail=tail) + BODY
    # the extension must not be *able* to reach Mutter's monitors.xml writer, even
    # by mistake: a symbol that is not described cannot be called from JS at all
    for sym in identifiers(text):
        for bad in FORBIDDEN:
            if bad in sym.lower():
                raise SystemExit("gen-gir: %s makes %s callable" % (ns, sym))
    return ns, text


def main(argv):
    check = "--check" in argv
    for i, a in enumerate(argv):
        if a == "--int" and i + 1 < len(argv):
            SIZES[argv[i + 1]] = (4, 4)
    header = gen = None
    for i, a in enumerate(argv):
        if a == "--from-header" and i + 1 < len(argv):
            header = argv[i + 1]
        if a == "--gen" and i + 1 < len(argv):
            gen = argv[i + 1]
    if header:
        return report_header(header, gen)
    args = [a for a in argv if not a.startswith("--")]
    skip = set()
    for i, a in enumerate(argv):
        if a in ("--from-header", "--gen", "--int"):
            skip.add(argv[i + 1] if i + 1 < len(argv) else None)
    args = [a for a in args if a not in skip]
    here = os.path.dirname(os.path.abspath(__file__))
    outdir = args[0] if args else os.path.join(
        os.path.dirname(here), "fuckwayland-overlap@fuckwayland", "typelib")
    os.makedirs(outdir, exist_ok=True)
    bad = 0
    for gen in sorted(BUILDS):
        ns, text = gir(gen)
        gpath = os.path.join(here, "%s-1.0.gir" % ns)
        tpath = os.path.join(outdir, "%s-1.0.typelib" % ns)
        tmp = tpath + ".new" if check else tpath
        if check:
            if not os.path.exists(gpath) or open(gpath).read() != text:
                print("stale: %s" % gpath)
                bad = 1
        else:
            with open(gpath, "w") as fh:
                fh.write(text)
        subprocess.run(["g-ir-compiler", "--includedir", "/usr/share/gir-1.0",
                        "-o", tmp, gpath if check else gpath], check=True)
        if check:
            old = open(tpath, "rb").read() if os.path.exists(tpath) else b""
            new = open(tmp, "rb").read()
            os.unlink(tmp)
            if old != new:
                print("stale: %s (%s != %s)"
                      % (tpath, hashlib.sha256(old).hexdigest()[:12],
                         hashlib.sha256(new).hexdigest()[:12]))
                bad = 1
        else:
            print("%s  %s  %s" % (ns, gpath, tpath))
    return bad


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
