#!/usr/bin/env python3
"""Generate (and compile) the type descriptions the overlap extension ships.

libmutter is built with hidden visibility, but the test-export macro expands to a real
export, so the four symbols the extension needs are ordinary dynamic symbols in the
shipped library -- absent from the introspection data, not from the library.  A GNOME
Shell extension can prepend its own search path and load a type description it ships
itself, which is what these files are.

Two properties of what is emitted here matter more than anything else in this tree:

**No pointer is ever declared as a pointer.**  Every pointer field in Mutter's private
structures is declared `guint64`, so reading one yields a *number* and gjs never
dereferences anything on our behalf.  Stepping from one struct to the next goes through
`g_memdup2(ptr, n)` -- a bounded copy of exactly n bytes -- and `g_strndup(ptr, n)` for
the connector strings, which lets the extension range-check the number against
`/proc/self/maps` before any address is read at all.  A wrong offset then produces
garbage or a refusal, not a SIGSEGV; with pointers declared as pointers it produced a
dead gnome-shell (measured, GNOME 50.1, docs/Technical.md section 6).

**Nothing that can write ~/.config/monitors.xml is declared.**
`meta_monitor_config_manager_save_current()` is not in the file, and neither is any
other `*save*` symbol, so no code in the extension can reach the writer even by
mistake.  `tests/test_gnome_overlap.py` asserts that about the shipped .gir and about
the shipped .typelib bytes.

The layout below is measured, not assumed (docs/Technical.md section 6): `parent_config`
and `switch_config` were proved with sentinels written through the exported accessors.
`logical_monitor_configs` is at offset 40 on both mutter 14 and mutter 18; the tail and
the total size are not the same, which is exactly why there is one description per
generation and why the extension refuses to run one against the other.

    offset  mutter 14 (GNOME 46)      mutter 18 (GNOME 50)
    0..23   GObject                   GObject
    24      parent_config             parent_config
    32      key                       key
    40      logical_monitor_configs   logical_monitor_configs
    48      disabled_monitor_specs    disabled_monitor_specs
    56      flags                     (unused)
    60      layout_mode               (unused)
    64      switch_config             (unused)
    68      padding                   layout_mode
    72      --                        switch_config
    76      --                        padding
    size    72                        80

Usage:  python3 gnome/overlap-typelib/gen-gir.py [OUTDIR]
        (OUTDIR defaults to gnome/fuckwayland-overlap@fuckwayland/typelib)

Needs `g-ir-compiler` (Ubuntu: libgirepository1.0-dev).  The compiled typelibs are
checked in because no desktop has that package installed; `--check` recompiles and
compares, which is how CI notices a .gir edited without a rebuild.
"""

import hashlib
import os
import subprocess
import sys

# generation -> (soname, ints between disabled_monitor_specs and layout_mode)
#   mutter 14: one (flags)      -> 56 + 4 + 12 = 72
#   mutter 18: three           -> 56 + 12 + 12 = 80
BUILDS = {
    14: ("libmutter-14.so.0", 1),
    18: ("libmutter-18.so.0", 3),
}

HEAD = '''<?xml version="1.0"?>
<!-- GENERATED by gnome/overlap-typelib/gen-gir.py -- do not edit by hand.
     Mutter {gen}'s private monitor-configuration structures, described so that no
     pointer in them is ever followed by the type system.  See that script. -->
<repository version="1.2"
            xmlns="http://www.gtk.org/introspection/core/1.0"
            xmlns:c="http://www.gtk.org/introspection/c/1.0"
            xmlns:glib="http://www.gtk.org/introspection/glib/1.0">
  <include name="GObject" version="2.0"/>
  <namespace name="{ns}" version="1.0" shared-library="{lib}"
             c:identifier-prefixes="Meta" c:symbol-prefixes="meta">

    <!-- MetaMonitorsConfig.  Every pointer is a guint64: a number, never a
         dereference. -->
    <record name="ConfigN" c:type="MetaMonitorsConfigN">
      <field name="g_class" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="ref_count" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="qdata" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="parent_config" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="key" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="logical_monitor_configs" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="disabled_monitor_specs" writable="1"><type name="guint64" c:type="guint64"/></field>
{tail}      <field name="layout_mode" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="switch_config" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="tail_pad" writable="1"><type name="gint" c:type="gint"/></field>
    </record>

    <!-- GList -->
    <record name="NodeN" c:type="MetaNodeN">
      <field name="data" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="next" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="prev" writable="1"><type name="guint64" c:type="guint64"/></field>
    </record>

    <!-- MetaLogicalMonitorConfig.  x is at +0 and y at +4: the only two words
         this extension ever writes. -->
    <record name="LMCN" c:type="MetaLMCN">
      <field name="x" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="y" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="width" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="height" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="monitor_configs" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="transform" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="scale" writable="1"><type name="gfloat" c:type="gfloat"/></field>
      <field name="is_primary" writable="1"><type name="gboolean" c:type="gboolean"/></field>
      <field name="is_presentation" writable="1"><type name="gboolean" c:type="gboolean"/></field>
    </record>

    <!-- MetaMonitorConfig -->
    <record name="MCN" c:type="MetaMCN">
      <field name="monitor_spec" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="mode_spec" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="enable_underscanning" writable="1"><type name="gint" c:type="gint"/></field>
      <field name="pad" writable="1"><type name="gint" c:type="gint"/></field>
    </record>

    <!-- MetaMonitorSpec -->
    <record name="MSN" c:type="MetaMSN">
      <field name="connector" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="vendor" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="product" writable="1"><type name="guint64" c:type="guint64"/></field>
      <field name="serial" writable="1"><type name="guint64" c:type="guint64"/></field>
    </record>

'''

TAIL_FIELD = ('      <field name="u{off}" writable="1">'
              '<type name="gint" c:type="gint"/></field>\n')


def _memdup(name, ret):
    """g_memdup2(number, n) -> a copy of exactly n bytes, read as `ret`."""
    return f'''    <function name="{name}" c:identifier="g_memdup2">
      <return-value transfer-ownership="none"><type name="{ret}" c:type="gpointer"/></return-value>
      <parameters>
        <parameter name="mem" transfer-ownership="none"><type name="guint64" c:type="guint64"/></parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>
'''


BODY = (
    _memdup('dup_cfg', 'ConfigN')
    + _memdup('dup_node', 'NodeN')
    + _memdup('dup_lmc', 'LMCN')
    + _memdup('dup_mc', 'MCN')
    + _memdup('dup_ms', 'MSN')
    + '''    <!-- a bounded copy of at most n bytes of a string -->
    <function name="strn" c:identifier="g_strndup">
      <return-value transfer-ownership="none"><type name="utf8" c:type="char*"/></return-value>
      <parameters>
        <parameter name="s" transfer-ownership="none"><type name="guint64" c:type="guint64"/></parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>

    <!-- the address of an object, as a number (g_object_ref returns its argument);
         every addr() is balanced by an unref_addr() -->
    <function name="addr" c:identifier="g_object_ref">
      <return-value transfer-ownership="none"><type name="guint64" c:type="guint64"/></return-value>
      <parameters><parameter name="o" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="unref_addr" c:identifier="g_object_unref">
      <return-value transfer-ownership="none"><type name="none" c:type="void"/></return-value>
      <parameters><parameter name="p" transfer-ownership="none"><type name="guint64" c:type="gpointer"/></parameter></parameters>
    </function>

    <!-- reads offset 0 only; GTypeInstance's first word is frozen ABI -->
    <function name="type_name" c:identifier="g_type_name_from_instance">
      <return-value transfer-ownership="none"><type name="utf8" c:type="char*"/></return-value>
      <parameters><parameter name="o" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>

    <!-- the exported-but-not-introspected monitor configuration API -->
    <function name="get_config_manager" c:identifier="meta_monitor_manager_get_config_manager">
      <return-value transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="get_current" c:identifier="meta_monitor_config_manager_get_current">
      <return-value transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="create_linear" c:identifier="meta_monitor_config_manager_create_linear">
      <return-value transfer-ownership="full"><type name="GObject.Object" c:type="gpointer"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="get_switch_config" c:identifier="meta_monitors_config_get_switch_config">
      <return-value transfer-ownership="none"><type name="gint" c:type="gint"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="set_switch_config" c:identifier="meta_monitors_config_set_switch_config">
      <return-value transfer-ownership="none"><type name="none" c:type="void"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="v" transfer-ownership="none"><type name="gint" c:type="gint"/></parameter></parameters>
    </function>
    <function name="verify" c:identifier="meta_verify_monitors_config" throws="1">
      <return-value transfer-ownership="none"><type name="gboolean" c:type="gboolean"/></return-value>
      <parameters><parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter></parameters>
    </function>
    <function name="apply" c:identifier="meta_monitor_manager_apply_monitors_config" throws="1">
      <return-value transfer-ownership="none"><type name="gboolean" c:type="gboolean"/></return-value>
      <parameters><parameter name="m" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="c" transfer-ownership="none"><type name="GObject.Object" c:type="gpointer"/></parameter>
                  <parameter name="method" transfer-ownership="none"><type name="gint" c:type="gint"/></parameter></parameters>
    </function>

    <!-- the write: four bytes at an address the reader has already range-checked -->
    <function name="wr" c:identifier="memcpy">
      <return-value transfer-ownership="none"><type name="guint64" c:type="gpointer"/></return-value>
      <parameters>
        <parameter name="dest" transfer-ownership="none"><type name="guint64" c:type="gpointer"/></parameter>
        <parameter name="src" transfer-ownership="none">
          <array c:type="gpointer" length="2"><type name="guint8" c:type="guint8"/></array>
        </parameter>
        <parameter name="n" transfer-ownership="none"><type name="guint64" c:type="gsize"/></parameter>
      </parameters>
    </function>
  </namespace>
</repository>
'''
)

FORBIDDEN = ("save", "write", "store", "persist")


def identifiers(text: str) -> list:
    """Every C symbol a type description makes callable."""
    out = []
    for line in text.splitlines():
        i = line.find('c:identifier="')
        if i >= 0:
            out.append(line[i + 14:line.index('"', i + 14)])
    return sorted(set(out))


def gir(gen: int) -> tuple:
    """(namespace, gir text) for one mutter generation."""
    lib, ints = BUILDS[gen]
    ns = "FwOverlap%d" % gen
    tail = "".join(TAIL_FIELD.format(off=56 + 4 * i) for i in range(ints))
    text = HEAD.format(gen=gen, ns=ns, lib=lib, tail=tail) + BODY
    # the extension must not be *able* to reach Mutter's monitors.xml writer, even
    # by mistake: a symbol that is not described cannot be called from JS at all
    for sym in identifiers(text):
        for bad in FORBIDDEN:
            if bad in sym.lower():
                raise SystemExit("gen-gir: %s makes %s callable" % (ns, sym))
    return ns, text


def main(argv):
    check = "--check" in argv
    args = [a for a in argv if not a.startswith("--")]
    here = os.path.dirname(os.path.abspath(__file__))
    outdir = args[0] if args else os.path.join(
        os.path.dirname(here), "fuckwayland-overlap@fuckwayland", "typelib")
    os.makedirs(outdir, exist_ok=True)
    bad = 0
    for gen in sorted(BUILDS):
        ns, text = gir(gen)
        gpath = os.path.join(here, "%s-1.0.gir" % ns)
        tpath = os.path.join(outdir, "%s-1.0.typelib" % ns)
        tmp = tpath + ".new" if check else tpath
        if check:
            if not os.path.exists(gpath) or open(gpath).read() != text:
                print("stale: %s" % gpath)
                bad = 1
        else:
            with open(gpath, "w") as fh:
                fh.write(text)
        subprocess.run(["g-ir-compiler", "--includedir", "/usr/share/gir-1.0",
                        "-o", tmp, gpath if check else gpath], check=True)
        if check:
            old = open(tpath, "rb").read() if os.path.exists(tpath) else b""
            new = open(tmp, "rb").read()
            os.unlink(tmp)
            if old != new:
                print("stale: %s (%s != %s)"
                      % (tpath, hashlib.sha256(old).hexdigest()[:12],
                         hashlib.sha256(new).hexdigest()[:12]))
                bad = 1
        else:
            print("%s  %s  %s" % (ns, gpath, tpath))
    return bad


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
